<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  takeaways: Array<{ takeaway: string; explanation: string }>
  title: string
}>()

const emit = defineEmits<{
  exportImage: []
}>()

const posterRef = ref<HTMLElement>()

const adinkraSymbols = ['◆', '◇', '▲', '●', '■', '★', '◈']
</script>

<template>
  <div>
    <div ref="posterRef" class="poster">
      <!-- Header -->
      <div class="poster-header">
        <div class="poster-pattern"></div>
        <h2 class="poster-title font-display">Key Takeaways</h2>
        <p class="poster-subtitle font-mono">{{ title }}</p>
        <div class="kente-stripe mt-3"></div>
      </div>

      <!-- Takeaways -->
      <div class="takeaway-list">
        <div
          v-for="(t, i) in takeaways"
          :key="i"
          class="takeaway-item"
        >
          <div class="takeaway-number">
            <span class="adinkra-symbol">{{ adinkraSymbols[i % adinkraSymbols.length] }}</span>
            <span class="number font-mono">{{ i + 1 }}</span>
          </div>
          <div class="takeaway-body">
            <h4 class="takeaway-title font-display">{{ t.takeaway }}</h4>
            <p class="takeaway-explain">{{ t.explanation }}</p>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="poster-footer">
        <div class="kente-stripe mb-2"></div>
        <p class="font-mono text-xs text-ink-faint">Generated by Jàngat</p>
      </div>
    </div>

    <button class="export-btn btn-primary mt-4 text-sm" @click="$emit('exportImage')">
      Export as Image
    </button>
  </div>
</template>

<style scoped>
.poster {
  background: linear-gradient(160deg, #0d0d2b 0%, #141430 50%, #1a1212 100%);
  border: 1px solid rgba(212, 160, 23, 0.15);
  border-radius: 20px;
  padding: 36px;
  max-width: 600px;
  position: relative;
  overflow: hidden;
}

.poster-header {
  text-align: center;
  margin-bottom: 28px;
  position: relative;
}

.poster-pattern {
  position: absolute;
  top: -20px;
  left: 50%;
  transform: translateX(-50%);
  width: 200px;
  height: 80px;
  opacity: 0.04;
  background: repeating-linear-gradient(
    45deg,
    var(--kente-gold) 0px,
    var(--kente-gold) 2px,
    transparent 2px,
    transparent 8px
  );
}

.poster-title {
  font-size: 1.5rem;
  color: var(--kente-gold);
  position: relative;
}

.poster-subtitle {
  font-size: 0.75rem;
  color: var(--ink-muted);
  margin-top: 4px;
}

.takeaway-list {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.takeaway-item {
  display: flex;
  gap: 16px;
  align-items: flex-start;
}

.takeaway-number {
  position: relative;
  flex-shrink: 0;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.adinkra-symbol {
  position: absolute;
  font-size: 2rem;
  color: var(--kente-gold);
  opacity: 0.15;
}

.number {
  position: relative;
  font-size: 0.85rem;
  font-weight: 700;
  color: var(--kente-gold);
}

.takeaway-body {
  flex: 1;
}

.takeaway-title {
  font-size: 0.95rem;
  color: var(--ink);
  line-height: 1.3;
}

.takeaway-explain {
  font-size: 0.8rem;
  color: var(--ink-muted);
  line-height: 1.5;
  margin-top: 4px;
}

.poster-footer {
  text-align: center;
  margin-top: 28px;
}

.export-btn {
  display: block;
}

@media (max-width: 768px) {
  .poster {
    padding: 20px 16px;
    border-radius: 14px;
    max-width: 100%;
  }

  .poster-title {
    font-size: 1.2rem;
  }

  .takeaway-item {
    gap: 12px;
  }

  .takeaway-number {
    width: 32px;
    height: 32px;
  }

  .adinkra-symbol {
    font-size: 1.5rem;
  }

  .takeaway-title {
    font-size: 0.88rem;
  }

  .takeaway-explain {
    font-size: 0.78rem;
  }

  .poster-header {
    margin-bottom: 20px;
  }

  .takeaway-list {
    gap: 16px;
  }

  .export-btn {
    width: 100%;
    min-height: 44px;
  }
}
</style>
